language: node_js
node_js:
  - 13.9.0
cache: npm
services:
  - redis-server
  - mysql
branches:
  only:
    - master

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - mysql test < migrations/init.sql
  - mysql test < migrations/applets.sql

install:
  - npm ci

script:
  - npm run lint
  - npm test