language: node_js
node_js:
  - 13.9.0
cache: npm
services:
  - redis-server
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - mysql -u travis --password="" < migrations/init.sql
  - mysql -u travis --password="" < migrations/applets.sql

install:
  - npm ci

script:
  - npm run lint
  - npm test